#pragma once

typedef enum {
    TOP_NEW_IMAGE,
    TOP_DRAW_RECT,
    TOP_DRAW_LINE,
    TOP_DITHER,
    TOP_DRAW_IMAGE,
    TOP_DRAW_TEXT,
    TOP_RESIZE_IMAGE,
    TOP_COLOR_TWEAKS,
    TOP_FLIP_IMAGE,
    TOP_ROTATE_IMAGE,
    
    TOP_PUSH_IMAGE,
    TOP_POP_IMAGE,
    
    TOP_IMAGE_GRAD_V,
    TOP_IMAGE_GRAD_H,
    TOP_IMAGE_GRAD_RAD,
    TOP_IMAGE_CHECKED,
    TOP_IMAGE_NOISE_WHITE,
    TOP_IMAGE_NOISE_PERLIN,
    TOP_IMAGE_CELLULAR,
    
    TOP_COLOR_REPLACE,
    
    TOP_IMAGE_ALPHA_MASK,
    TOP_IMAGE_ALPHA_MASK_CLEAR,
    
    TOP_DROP_IMAGE,
    TOP_DRAW_IMAGE_INSTANCE,
    TOP_CLONE_IMAGE,
    
    TOP_BLUR_IMAGE,
    
    TOP_TRACE_LAMP,
    TOP_TRACE_SUN,
    TOP_TRACE_RESERVED2,
    TOP_TRACE_RESERVED3,
    TOP_TRACE_RESERVED4,
    TOP_TRACE_RESERVED5,
    
    TOP_FORCE_UINT8 = UINT8_MAX
} td_op_kind;
