name: Deploy on itch.io

on:
  workflow_dispatch

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    
    - name: Set version variable
      shell: bash
      run: |
        VER=$(cat code/app/texed.c | sed -nr "s/.*TEXED_VERSION\s*\"(.*)\".*/\1/p")
        echo "VERSION=$VER >> $GITHUB_ENV"
        
    - name: Setup dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update -qq
        sudo apt-get install gcc-multilib
        sudo apt-get install -y --no-install-recommends libglfw3 libglfw3-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev

    - name: Configure CMake (Windows)
      if: matrix.os == 'windows-latest'
      run: cmake -B ${{github.workspace}}/build -T ClangCL
      
    - name: Configure CMake
      if: matrix.os != 'windows-latest'
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
        
    - name: Package
      shell: bash
      run: |
        mkdir deploy
        cp -r art deploy/
        cp ${{github.workspace}}/build/Release/* deploy/

    - name: Push to itch.io
      uses: zaklaus/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: ${{ matrix.os }}
        ITCH_GAME: texed
        ITCH_USER: zaklaus
        PACKAGE: deploy
        VERSION: ${{ env.VERSION }}
