name: Deploy on itch.io

on:
  workflow_dispatch

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update -qq
        sudo apt-get install gcc-multilib
        sudo apt-get install -y --no-install-recommends libglfw3 libglfw3-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev

    - name: Configure CMake (Windows)
      if: matrix.os == 'windows-latest'
      run: cmake -B build -T ClangCL
      
    - name: Configure CMake
      if: matrix.os != 'windows-latest'
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}}
        
    - name: Package
      shell: bash
      run: |
        mkdir deploy
        cp -r art deploy/
        cp build/Release/* deploy/
        
    - name: Push butler (Windows)
      if: matrix.os == 'windows-latest'
      shell: bash
      run: |
        curl -L -o butler.zip https://broth.itch.ovh/butler/windows-amd64/LATEST/archive/default
        unzip butler.zip
        ./butler.exe -V
        export BUTLER_API_KEY=${{ secrets.BUTLER_CREDENTIALS }}
        ./butler.exe push "deploy" zaklaus/texed:win64 --userversion $(cat code/app/texed.c | sed -nr "s/.*TEXED_VERSION\s*\"(.*)\".*/\1/p")
        
    - name: Push butler (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
        unzip butler.zip
        chmod +x butler
        ./butler -V
        export BUTLER_API_KEY=${{ secrets.BUTLER_CREDENTIALS }}
        ./butler push "deploy" zaklaus/texed:ubuntu --userversion $(cat code/app/texed.c | sed -nr "s/.*TEXED_VERSION\s*\"(.*)\".*/\1/p")
